spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
server:
  port: 8080

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

app:
  frontendServiceClientName: frontendService
  databaseServiceClientName: databaseService