spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
server:
  port: 8080
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: ERROR
app:
  url: https://www.originsro-market.de/sells/item_id/
  checkTime: 300000
bot:
  name: MarketObserver
  token: 123