/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.math.LongMath;

public class SomethingFromGuava {
    public static void main(String... args) {
        for (int i = 0; i < 25; i++) {
            try {
                System.out.println(LongMath.factorial(i));
                Thread.sleep(50);
            } catch (InterruptedException ex) {
                System.out.println("Логирование в консоль =)");
            }
        }
    }
}
